apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: venki
  name: venki
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: venki
    spec:
      containers:
      - image: kasareddy143/devopsworkflow
        name: venki
        ports:
        - name: venki
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: venki
  labels:
    app: venki
spec:
  selector:
    app: venki
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080

